apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8srestart.fullname" . }}
  labels:
    {{- include "k8srestart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - patch
